# Generated by Django 2.2.9 on 2020-01-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0002_avalimage_firmaimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=60),
        ),
    ]
